# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PetMeApp-MVF4' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PetMeApp-MVF4
  pod 'Firebase/Analytics'
  pod 'Firebase/Core'
  pod 'FirebaseUI'
  pod 'FirebaseUI/Auth'
  pod 'Firebase/Database'
  pod 'FirebaseUI/Storage'



end
